### ISSUE TITLE
Often happens "Could not pass event InventoryClickEvent to MIGS"

### ISSUE THREAD

**Issue by Leo1003** [PenguinOwl/minecraft-interactive-gui-shops#2]
It seems like the event handler doesn't check something which is null
```
[08:05:11 ERROR]: Could not pass event InventoryClickEvent to MIGS v1.8.5                                                                                                                      
org.bukkit.event.EventException                                                                                                                                                                
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                        
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                          
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                        
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                        
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1849) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                         
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                               
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                               
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                             
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]                                                                                               
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]                                                                                                              
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                                           
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                            
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                            
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                            
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                          
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]                                                                                                                                 
Caused by: java.lang.NullPointerException                                                                                                                                                      
        at penowl.plugin.migs.ClickListener.someoneKnocked(ClickListener.java:35) ~[?:?]                                                                                                       
        at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]                                                                                                                
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]                                                                                
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]                                                                                                                     
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]                                                        
        ... 15 more
```

**Comment by PenguinOwl** [comment]
Fixed in 1.8.7
