### ISSUE TITLE
Issues with passing events MIGS

### ISSUE THREAD

**Issue by sjaustad** [PenguinOwl/minecraft-interactive-gui-shops#7]
Minecraft Version: 1.12.2
MIGS: 1.11.2, 1.8.7

Possible conflicting mods:
Towny v93

Server Setup: Cat server for Forge mods and Bukkit plugins. 

Problem: The shop mod was working fine for about a day but then all of a sudden the server throws this error every single time a block is placed or destroyed:

```
[12:32:36] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MIGS v1.11.2
org.bukkit.event.EventException: null
        at catserver.server.executor.ReflectionExecutor.execute(ReflectionExecutor.java:36) ~[ReflectionExecutor.class:git-4b6a920-Community]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1127) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchFieldError: ACACIA_WALL_SIGN
        at penowl.plugin.migs.InteractListener.someoneBlocked(InteractListener.java:51) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at catserver.server.executor.ReflectionExecutor.execute(ReflectionExecutor.java:32) ~[ReflectionExecutor.class:git-4b6a920-Community]
        ... 17 more
```

I am not sure why this issue showed up about a day later, but I've tried removing permissions and towny and it still didn't work.

**Comment by sjaustad** [comment]
I solved the issue. Version 1.11.2 of MIGS does NOT work with 1.12.2 Minecraft, which is fine because it is listed as only supporting version 1.14. The issue, however, is that v1.8.7 of MIGS auto-updates itself the first time you launch it but requires a restart in order to load the newest version (1.11.2). I opened the Jar file with Winrar and edited config.yml setting "Auto Update" to false. 

I am not sure if MIGS had a trouble identifying my version of Minecraft running on the server or if it just auto updates, but this does seem to be an issue because it updates itself to a broken version for 1.12.2 Minecraft.
